id: IA8645398
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:21:13+00:00'
last_modified: '2022-06-08T18:05:46.771720+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W7616
  title: མན་ངག་གནད་འགག་དོ་ཤལ་མཛེས་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EB9C:
      image_group_id: I1PD103597
      title: Volume 1 of man ngag gnad 'gag do shal mdzes rgyan
      total_pages: 124
      order: 1
      base_file: EB9C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
