id: P008053
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:58:11.122454
source_metadata:
  id: bdr:W7616
  title: མན་ངག་གནད་འགག་དོ་ཤལ་མཛེས་རྒྱན
  author: ''
  volumes:
    c88aa0ee99194591a50dc3a95a0ebfe3:
      image_group_id: I1PD103597
      title: Volume 1 of man ngag gnad 'gag do shal mdzes rgyan
      volume_number: 1
      total_pages: 124
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
