id: P008053
initial_creation_type: ocr
source_metadata:
  id: bdr:W7616
  title: མན་ངག་གནད་འགག་དོ་ཤལ་མཛེས་རྒྱན
  author: ''
  volumes:
    75c219103d2345e49759df028ee0893e:
      image_group_id: I1PD103597
      title: ''
      volume_number: 1
      total_pages: 124
ebook_metadata:
  title: མན་ངག་གནད་འགག་དོ་ཤལ་མཛེས་རྒྱན
  author: ''
  sku: P008053
  cover: cover.jpg
  layers:
  - pagination
